In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
first = pd.read_pickle('/mnt/disk07/user/pzhang84/data/wrong_combination_neg_samples/embeddings/catELMo_wo_pooling.pkl')
second = pd.read_pickle('/mnt/disk07/user/pzhang84/data/wrong_combination_neg_samples/embeddings/catELMo_wo_pooling2.pkl')

a = first.head(150008)
b = second.tail(150008)

combined = pd.concat([a,b])

In [17]:
combined.to_pickle('/mnt/disk07/user/pzhang84/data/wrong_combination_neg_samples/embeddings/catELMo_wo_pooling_combined.pkl')

In [27]:
combined

,epi,tcr,binding,tcr_embeds,epi_embeds
0,EAAGIGILTV,CASSLGNEQF,1,"[[-0.3007097542285919, 0.05361589416861534, 0....","[[0.3195067346096039, 0.086360402405262, 0.195..."
1,EAAGIGILTV,CASSLGVATGELF,1,"[[-0.299367755651474, 0.057464782148599625, 0....","[[0.831741452217102, 0.2774326801300049, -0.16..."
2,EAAGIGILTV,CASSQEEGGGSWGNTIYF,1,"[[-0.3027852475643158, 0.05087145417928696, 0....","[[0.720084547996521, 0.11275053024291992, 0.04..."
3,EAAGIGILTV,CASSQEGLAGASQYF,1,"[[-0.3028606176376343, 0.05600085109472275, 0....","[[0.5722309947013855, 0.19283819198608398, 0.1..."
4,EAAGIGILTV,CASSQETDIVFNOPQHF,1,"[[-0.30248111486434937, 0.05205222964286804, 0...","[[0.2880273461341858, -0.07931049913167953, -0..."
...,...,...,...,...,...
300011,AYSNNSIAIPTNFTISV,CASSPRTGQNSPLHF,0,"[[-0.30954408645629883, 0.1671132892370224, 0....","[[0.06045852601528168, -0.1596667468547821, -0..."
300012,NPLLYDANYFLCW,CAISESRGDSYNEQFF,0,"[[-0.4396389126777649, 0.2558208107948303, 0.1...","[[0.43053311109542847, -0.025182202458381653, ..."
300013,KLGGALQAK,CASSLVGADRSGELFF,0,"[[-0.22806274890899658, 0.3048815131187439, 0....","[[0.4761084318161011, -0.28149741888046265, -0..."
300014,GLCTLVAML,CASSEGSYTEAFF,0,"[[-0.33263421058654785, 0.13186562061309814, 0...","[[0.5136846303939819, -0.07884438335895538, 0...."
300015,RAKFKQLL,CASSLGGSNYEQYF,0,"[[-0.3287348449230194, 0.136297345161438, 0.18...","[[1.1024035215377808, -0.23083291947841644, 0...."

In [18]:
combined

,epi,tcr,binding,tcr_embeds,epi_embeds
0,EAAGIGILTV,CASSLGNEQF,1,"[[-0.3007097542285919, 0.05361589416861534, 0....","[[0.3195067346096039, 0.086360402405262, 0.195..."
1,EAAGIGILTV,CASSLGVATGELF,1,"[[-0.299367755651474, 0.057464782148599625, 0....","[[0.831741452217102, 0.2774326801300049, -0.16..."
2,EAAGIGILTV,CASSQEEGGGSWGNTIYF,1,"[[-0.3027852475643158, 0.05087145417928696, 0....","[[0.720084547996521, 0.11275053024291992, 0.04..."
3,EAAGIGILTV,CASSQEGLAGASQYF,1,"[[-0.3028606176376343, 0.05600085109472275, 0....","[[0.5722309947013855, 0.19283819198608398, 0.1..."
4,EAAGIGILTV,CASSQETDIVFNOPQHF,1,"[[-0.30248111486434937, 0.05205222964286804, 0...","[[0.2880273461341858, -0.07931049913167953, -0..."
...,...,...,...,...,...
300011,AYSNNSIAIPTNFTISV,CASSPRTGQNSPLHF,0,"[[-0.30954408645629883, 0.1671132892370224, 0....","[[0.06045852601528168, -0.1596667468547821, -0..."
300012,NPLLYDANYFLCW,CAISESRGDSYNEQFF,0,"[[-0.4396389126777649, 0.2558208107948303, 0.1...","[[0.43053311109542847, -0.025182202458381653, ..."
300013,KLGGALQAK,CASSLVGADRSGELFF,0,"[[-0.22806274890899658, 0.3048815131187439, 0....","[[0.4761084318161011, -0.28149741888046265, -0..."
300014,GLCTLVAML,CASSEGSYTEAFF,0,"[[-0.33263421058654785, 0.13186562061309814, 0...","[[0.5136846303939819, -0.07884438335895538, 0...."
300015,RAKFKQLL,CASSLGGSNYEQYF,0,"[[-0.3287348449230194, 0.136297345161438, 0.18...","[[1.1024035215377808, -0.23083291947841644, 0...."

# 1. load data and get trainValid/test split

In [28]:
def load_data_split(dat,split_type, seed):
    n_fold = 5
    idx_test_fold = 0
    idx_val_fold = -1
    idx_test = None
    idx_train = None
    x_pep = dat.epi
    x_tcr = dat.tcr
    
    if split_type == 'random':
        n_total = len(x_pep)
    elif split_type == 'epi':
        unique_peptides = np.unique(x_pep)
        n_total = len(unique_peptides)
    elif split_type == 'tcr':
        unique_tcrs = np.unique(x_tcr)
        n_total = len(unique_tcrs)
        
    np.random.seed(seed)    
    idx_shuffled = np.arange(n_total)
    np.random.shuffle(idx_shuffled)
    
    # Determine data split from folds
    n_test = int(round(n_total / n_fold))
    n_train = n_total - n_test

    # Determine position of current test fold
    test_fold_start_index = idx_test_fold * n_test
    test_fold_end_index = (idx_test_fold + 1) * n_test

    if split_type == 'random':
        # Split data evenly among evenly spaced folds
        # Determine if there is an outer testing fold
        if idx_val_fold < 0:
            idx_test = idx_shuffled[test_fold_start_index:test_fold_end_index]
            idx_train = list(set(idx_shuffled).difference(set(idx_test)))
        else:
            validation_fold_start_index = args.idx_val_fold * n_test
            validation_fold_end_index = (args.idx_val_fold + 1) * n_test
            idx_test_remove = idx_shuffled[test_fold_start_index:test_fold_end_index]
            idx_test = idx_shuffled[validation_fold_start_index:validation_fold_end_index]
            idx_train = list(set(idx_shuffled).difference(set(idx_test)).difference(set(idx_test_remove)))
    elif split_type == 'epi':
        if idx_val_fold < 0:
            idx_test_pep = idx_shuffled[test_fold_start_index:test_fold_end_index]
            test_peptides = unique_peptides[idx_test_pep]
            idx_test = [index for index, pep in enumerate(x_pep) if pep in test_peptides]
            idx_train = list(set(range(len(x_pep))).difference(set(idx_test)))
        else:
            validation_fold_start_index = args.idx_val_fold * n_test
            validation_fold_end_index = (args.idx_val_fold + 1) * n_test
            idx_test_remove_pep = idx_shuffled[test_fold_start_index:test_fold_end_index]
            test_remove_peptides = unique_peptides[idx_test_remove_pep]
            idx_test_pep = idx_shuffled[validation_fold_start_index:validation_fold_end_index]
            test_peptides = unique_peptides[idx_test_pep]
            idx_test = [index for index, pep in enumerate(x_pep) if pep in test_peptides]
            idx_test_remove = [index for index, pep in enumerate(x_pep) if pep in test_remove_peptides]
            idx_train = list(set(range(len(x_pep))).difference(set(idx_test)).difference(set(idx_test_remove)))
    elif split_type == 'tcr':
        if idx_val_fold < 0:
            idx_test_tcr = idx_shuffled[test_fold_start_index:test_fold_end_index]
            test_tcrs = unique_tcrs[idx_test_tcr]
            idx_test = [index for index, tcr in enumerate(x_tcr) if tcr in test_tcrs]
            idx_train = list(set(range(len(x_tcr))).difference(set(idx_test)))
        else:
            validation_fold_start_index = args.idx_val_fold * n_test
            validation_fold_end_index = (args.idx_val_fold + 1) * n_test
            idx_test_remove_tcr = idx_shuffled[test_fold_start_index:test_fold_end_index]
            test_remove_tcrs = unique_tcrs[idx_test_remove_tcr]
            idx_test_tcr = idx_shuffled[validation_fold_start_index:validation_fold_end_index]
            test_tcrs = unique_tcrs[idx_test_tcr]
            idx_test = [index for index, tcr in enumerate(x_tcr) if tcr in test_tcrs]
            idx_test_remove = [index for index, tcr in enumerate(x_tcr) if tcr in test_remove_tcrs]
            idx_train = list(set(range(len(x_tcr))).difference(set(idx_test)).difference(set(idx_test_remove)))

    testData = dat.iloc[idx_test, :].sample(frac=1).reset_index(drop=True)
    trainData = dat.iloc[idx_train, :].sample(frac=1).reset_index(drop=True)
    

    print('================check Overlapping========================')
    print('number of overlapping tcrs: ', str(len(set(trainData.tcr).intersection(set(testData.tcr)))))
    print('number of overlapping epitopes: ', str(len(set(trainData.epi).intersection(set(testData.epi)))))
    
    return trainData, testData

In [3]:
dat = pd.read_pickle('/mnt/disk07/user/pzhang84/data/tcr_repertoires_healthy_samples/combined_dataset_repTCRs/catELMo_wo_pooling_combined.pkl')
trainData, testData = load_data_split(dat,'tcr', 42)

================check Overlapping========================
number of overlapping tcrs:  0
number of overlapping epitopes:  735

In [29]:
trainData, testData = load_data_split(combined,'epi', 42)

================check Overlapping========================
number of overlapping tcrs:  43292
number of overlapping epitopes:  0

# 2. pad/truncate -> 22x1024

In [30]:
def padding_helper(seq, padded_len=22):
    if len(seq) >= padded_len:
        seq = seq[:padded_len]
    else:
        suf = [0] * 1024
        while len(seq) < padded_len:
            seq.append(suf)
    return seq

# pad trainValid
for i in tqdm(range(len(trainData))):
    trainData.tcr_embeds[i] = padding_helper(trainData.tcr_embeds[i])
    trainData.epi_embeds[i] = padding_helper(trainData.epi_embeds[i])
    
# pad testing
for i in tqdm(range(len(testData))):
    testData.tcr_embeds[i] = padding_helper(testData.tcr_embeds[i])
    testData.epi_embeds[i] = padding_helper(testData.epi_embeds[i])

  0%|          | 0/232640 [00:00<?, ?it/s]/home/pzhang84/.conda/envs/tf26/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/home/pzhang84/.conda/envs/tf26/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 232640/232640 [28:11<00:00, 137.54it/s]
  0%|          | 0/67376 [00:00<?, ?it/s]/home/pzhang84/.conda/envs/tf26/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/pzhang84/.conda/envs/tf26/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 67376/67376 [02:04<00:00, 541.54it/s]

# 3. Training and validation split

In [31]:
trainValid = trainData.sample(frac=1).reset_index(drop=True)
print('Totally length of training and validation is ' + str(len(trainValid)))

Totally length of training and validation is 232640

In [32]:
## split into train and valid part

'''
Wrong combination Data summary

                Train    Valid    Test
TCR split       191864   47967    60185
Epitope split   186112   46528    67376

'''
import math
n_split = int(math.floor(len(trainValid)*0.8))
train = trainValid.head(n_split).reset_index(drop=True)
valid = trainValid.tail(len(trainValid) - n_split).reset_index(drop=True)

print('Length of train data is ' + str(n_split))
print('Length of valid data is ' + str(len(trainValid) - n_split))

Length of train data is 186112
Length of valid data is 46528

In [33]:
## save train, valid and testData into pickles
train.to_pickle('data_wrong_comb/seed42_epi_split/trainData.pkl')
valid.to_pickle('data_wrong_comb/seed42_epi_split/validData.pkl')
testData.to_pickle('data_wrong_comb/seed42_epi_split/testData.pkl')

# 4. npz-lize pickle file for TCR split

In [34]:
def divide_df(dat, mode):
    """
    mode -- train, test, valid
    """
    for i in tqdm(range(len(dat))):
        x_tcr = np.array(dat.tcr_embeds[i])
        x_epi = np.array(dat.epi_embeds[i])
        y = np.array(dat.binding[i])
        
        # save individual npz
        np.savez('data_wrong_comb/seed42_epi_split/'+ mode + '/' + str(i), x_tcr=x_tcr, x_epi=x_epi, y=y) 

divide_df(dat = train, mode = 'train')
divide_df(dat = valid, mode = 'valid')
divide_df(dat = testData, mode = 'test')

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 186112/186112 [10:03<00:00, 308.47it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 46528/46528 [02:27<00:00, 315.16it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 67376/67376 [03:30<00:00, 319.59it/s]

# 5. Save testData labels

In [35]:
testData.tcr_embeds = None
testData.epi_embeds = None
testData.to_pickle('./data_wrong_comb/seed42_epi_split/testData_labels.pkl')

# 6. Check if the seed generated same testing data

In [13]:
testData_old = pd.read_pickle('./data/seed42_tcr_split_old/testData_labels.pkl')
testData_old

,epi,tcr,binding,tcr_embeds,epi_embeds
0,MIELSLIDFYLCFLAFLLFLVLIML,CSASTNEGGQETQYF,1,None,None
1,SELVIGAVIL,CARGTGGANVLTF,1,None,None
2,TPINLVRDL,CSVVPRSIGTDTQYF,1,None,None
3,GLCTLVAML,CATSRRGRGNGNQPQHF,0,None,None
4,LITLATCELYHYQECV,CASRHRDSLWYNEQFF,1,None,None
...,...,...,...,...,...
59932,KLGGALQAK,CASSDTQGAHYGYTF,0,None,None
59933,YVLDHLIVV,CASSTTSGPTYEQYF,0,None,None
59934,LLLDDFVEII,CASSELSFPHGGELFF,0,None,None
59935,KLGGALQAK,CSGSEGNTIYF,1,None,None
59936,RQLLFVVEV,CASSPRGAMGHEQFF,0,None,None

In [14]:
testData

,epi,tcr,binding,tcr_embeds,epi_embeds
0,MIELSLIDFYLCFLAFLLFLVLIML,CSASTNEGGQETQYF,1,None,None
1,SELVIGAVIL,CARGTGGANVLTF,1,None,None
2,TPINLVRDL,CSVVPRSIGTDTQYF,1,None,None
3,GLCTLVAML,CATSRRGRGNGNQPQHF,0,None,None
4,LITLATCELYHYQECV,CASRHRDSLWYNEQFF,1,None,None
...,...,...,...,...,...
59932,KLGGALQAK,CASSDTQGAHYGYTF,0,None,None
59933,YVLDHLIVV,CASSTTSGPTYEQYF,0,None,None
59934,LLLDDFVEII,CASSELSFPHGGELFF,0,None,None
59935,KLGGALQAK,CSGSEGNTIYF,1,None,None
59936,RQLLFVVEV,CASSPRGAMGHEQFF,0,None,None